### register user

POST http://localhost:3000/users/register
Content-Type: application/json

{
  "email": "shay@gmail.com",
  "password": "1234"
}

### login user

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "email": "shay@gmail.com",
  "password": "1234"
}

### logout user

POST http://localhost:3000/users/logout

### refresh user token

POST http://localhost:3000/users/refresh-token
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjk0OTkyNjQ0NTE2ODk0OTgiLCJpYXQiOjE3MzQ5ODk1NDYsImV4cCI6MTczNTU5NDM0Nn0._BAEqV-gMJKw1qf1JYQMTX2qHDJMQAxkh4CdzHXemKw"
}

### get all posts

GET http://localhost:3000/posts

### create post

POST http://localhost:3000/posts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjkzODA3ODQ0NjAxMDYzNjQiLCJpYXQiOjE3MzUwNjI1NDgsImV4cCI6MTczNTA2MjcyOH0.HU8mwKaSRv-NNPmdaUQKtMFcfUGey1EBogXLZXvg5_k

{
  "title": "Hello",
  "content": "Hello World..."
}

### get a post by id

GET http://localhost:3000/posts/6766a618ae43ada7486ebcd9

### get posts by userId

GET http://localhost:3000/posts?filter=6769d45d3130b8508d0f1ebc

### update post

PUT http://localhost:3000/posts/676af45a95744112ba44c549
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjkzODA3ODQ0NjAxMDYzNjQiLCJpYXQiOjE3MzUwNjI1NDgsImV4cCI6MTczNTA2MjcyOH0.HU8mwKaSRv-NNPmdaUQKtMFcfUGey1EBogXLZXvg5_k

{
  "content": "how are you?"
}

### delete post

DELETE http://localhost:3000/posts/676af45a95744112ba44c549
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjkzODA3ODQ0NjAxMDYzNjQiLCJpYXQiOjE3MzUwNjI1NDgsImV4cCI6MTczNTA2MjcyOH0.HU8mwKaSRv-NNPmdaUQKtMFcfUGey1EBogXLZXvg5_k

### add a comment to a post

POST http://localhost:3000/comments
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjMyNzIyNTEwMTQ5Mzk0OTM0IiwiaWF0IjoxNzM1MDYwOTU5LCJleHAiOjE3MzUwNjExMzl9.xzi046MlKw0oVWXlIjHSdIU092jmWTvQ55ZqNrr_Bm0

{
  "postId": "676aedf5569cdb7d89d4fafb",
  "content": "my first comment"
}

### get all comments

GET http://localhost:3000/comments

### get all comments of a post

GET http://localhost:3000/comments?filter=6766a606ae43ada7486ebcd1

### get comment by id

GET http://localhost:3000/comments/6765c0f4ab06290e54a37632

### update comment

PUT http://localhost:3000/comments/6766a66dae43ada7486ebce6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjkzODA3ODQ0NjAxMDYzNjQiLCJpYXQiOjE3MzUwNjI1NDgsImV4cCI6MTczNTA2MjcyOH0.HU8mwKaSRv-NNPmdaUQKtMFcfUGey1EBogXLZXvg5_k

{
  "content": "my edited comment"
}

### delete comment

DELETE http://localhost:3000/comments/6765c0f4ab06290e54a37632
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzY5ZDQ1ZDMxMzBiODUwOGQwZjFlYmMiLCJyYW5kb20iOiIwLjkzODA3ODQ0NjAxMDYzNjQiLCJpYXQiOjE3MzUwNjI1NDgsImV4cCI6MTczNTA2MjcyOH0.HU8mwKaSRv-NNPmdaUQKtMFcfUGey1EBogXLZXvg5_k